src/Entity/Page.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\PageRepository")
 */
class Page
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $slug;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $title;


    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $text;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $meta_title;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $meta_desc;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $meta_keywords;

    public function __toString()
    {
        return (string)$this->title;
    }

    public function getId()
    {
        return $this->id;
    }

    public function getSlug(): ?string
    {
        return $this->slug;
    }

    public function setSlug(string $slug): self
    {
        $this->slug = $slug;

        return $this;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): self
    {
        $this->title = $title;

        return $this;
    }

    public function getText(): ?string
    {
        return $this->text;
    }

    public function setText(?string $text): self
    {
        $this->text = $text;

        return $this;
    }

    public function getMetaTitle(): ?string
    {
        return $this->meta_title;
    }

    public function setMetaTitle(?string $meta_title): self
    {
        $this->meta_title = $meta_title;

        return $this;
    }

    public function getMetaDesc(): ?string
    {
        return $this->meta_desc;
    }

    public function setMetaDesc(?string $meta_desc): self
    {
        $this->meta_desc = $meta_desc;

        return $this;
    }

    public function getMetaKeywords(): ?string
    {
        return $this->meta_keywords;
    }

    public function setMetaKeywords(?string $meta_keywords): self
    {
        $this->meta_keywords = $meta_keywords;

        return $this;
    }
}

src/Entity/Service.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\ServiceRepository")
 * @ORM\HasLifecycleCallbacks()
 */
class Service
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $name;

    /**
     * @ORM\Column(type="text")
     */
    private $description;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $price;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $color;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $image;

    public function __toString()
    {
        return (string)$this->name;
    }

    public function getId()
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getPrice(): ?string
    {
        return $this->price;
    }

    public function setPrice(?string $price): self
    {
        $this->price = $price;

        return $this;
    }

    public function getColor(): ?string
    {
        return $this->color;
    }

    public function setColor(?string $color): self
    {
        $this->color = $color;

        return $this;
    }

    public function getImage(): ?string
    {
        return $this->image;
    }

    public function setImage($image)
    {
        if (null === $image) {
            return $this;
        }

        $image->move(
            '/home/u212057/upitel.tech/www/uploads/',
            $image->getClientOriginalName()
        );

        $this->image = $image->getClientOriginalName();

        return $this;
    }
}

src/Entity/Work.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\WorkRepository")
 */
class Work
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $name;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $description;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $link;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $image;

    public function __toString(): ?string
    {
        return (string)$this->name;
    }

    public function getId()
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(?string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getLink(): ?string
    {
        return $this->link;
    }

    public function setLink(?string $link): self
    {
        $this->link = $link;

        return $this;
    }

    public function getImage(): ?string
    {
        return $this->image;
    }

    public function setImage($image)
    {
        if (null === $image) {
            return $this;
        }

        $image->move(
            '/home/u212057/upitel.tech/www/uploads/',
            $image->getClientOriginalName()
        );

        $this->image = $image->getClientOriginalName();

        return $this;
    }
}

src/Controller/DefaultController.php
<?php

namespace App\Controller;

use Symfony\Component\Routing\Annotation\Route;
use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Bundle\FrameworkBundle\Console\Application;
use Symfony\Component\Console\Input\ArrayInput;
use Symfony\Component\Console\Output\BufferedOutput;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\HttpKernel\KernelInterface;
use Symfony\Component\Security\Http\Authentication\AuthenticationUtils;
use App\Entity\Service;
use App\Entity\Work;
use App\Entity\Page;

class DefaultController extends Controller
{
    /**
     * @var KernelInterface
     */
    private $kernel;

    public function __construct(KernelInterface $kernel)
    {
        $this->kernel = $kernel;
    }

    /**
     * @Route("/", name="index")
     */
    public function index()
    {
        return $this->render('default/index.html.twig', [
        	'services' => $this->getDoctrine()->getRepository(Service::class)->findAll(),
            'works' => $this->getDoctrine()->getRepository(Work::class)->findAll(),
            'page' => $this->getDoctrine()->getRepository(Page::class)->findOneBy(['slug' => '/']) 
        ]);
    }


    /**
     * @Route("/clear_cache", name="clear_cache")
     * @param KernelInterface $kernel
     */
    public function clearCache(KernelInterface $kernel)
    {
        $application = new Application($kernel);
        $application->setAutoExit(false);

        $input = new ArrayInput(array(
           'command' => 'cache:clear'
        ));

        $output = new BufferedOutput();
        $application->run($input, $output);

        $content = $output->fetch();

        return new Response($content);
    }

    /**
     * @Route("/login", name="login")
     */
    public function login(Request $request, AuthenticationUtils $authenticationUtils)
    {
        $error = $authenticationUtils->getLastAuthenticationError();
        $lastUsername = $authenticationUtils->getLastUsername();

        return $this->render('security/login.html.twig', array(
            'last_username' => $lastUsername,
            'error'         => $error,
        ));
    }    
    /**
     * @Route("/{slug}", name="static")
     */
    public function static($slug)
    {
        $page = $this->getDoctrine()->getRepository(Page::class)->findOneBy(['slug' => $slug]);

        if (!$page) {
            throw $this->createNotFoundException('Страница не найдена');
        }

        return $this->render('default/page.html.twig', [
            'page' => $page
        ]);
    }
}

templates/base.html.twig
<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8">
		<meta name="viewport" content="width=device-width, initial-scale=1, minimum-scale=1, maximum-scale=1">
		<meta name="format-detection" content="telephone=no">
        {% block meta %}{% endblock %}
        <title>{% block title %}Разработка сайтов на 1С-Битрикс - Uptel{% endblock %}</title>
        <link rel="stylesheet" href="/css/main.css">
        <link rel="stylesheet" href="/scripts/arcticmodal/jquery.arcticmodal.css">
        {% block stylesheets %}{% endblock %}
    </head>
    <body>
        {% block body %}{% endblock %}
        <script src="/scripts/main.min.js"></script>
        <script src="/scripts/jquery.maskedinput.min.js"></script>
        {% block javascripts %}{% endblock %}
    </body>
</html>

templates/default/index.html.twig
{% extends 'base.html.twig' %}

{% if page %}
{% block title %}{{ page.title }}{% endblock %}
{% block meta %}
		{% if page.metaTitle %}
		<meta name="title" content="{{ page.metaTitle }}">
		{% endif %}
		{% if page.metaDesc %}
		<meta name="description" content="{{ page.metaDesc }}">
		{% endif %}
		{% if page.metaKeywords %}
		<meta name="keywords" content="{{ page.metaKeywords }}">
		{% endif %}
{% endblock %}
{% endif %}

{% block body %}
	<div class="first-screen" style="background-image:url(img/first-screen-bg.jpg);">
		<div class="first-screen__overlay"></div>
		<div class="first-screen__content">
			<div class="container">
				<div class="first-screen__content-title">Создание и обслуживание интернет-проектов.</div>
				<div class="first-screen__content-sub-title">За всё время работы реализовано более 500 проектов.</div>

				<a href="javascript:void(0);" data-href="#request" class="first-screen__content-link js-popup-link">Оставить заявку</a>
				<div class="first-screen__sign-text">
					Оставьте заявку и с вами свяжутся наши сотрудники <span>в течение нескольких часов</span>
				</div>
			</div>
		</div>
		<header class="header">
			<div class="container clearfix">
				<a href="/" class="header__logo">
					<span class="header__logo-text">Разработка современных<br>интернет-проектов.</span>
				</a>
				<div class="header__phone">
					<p class="header__phone-number">(495) 627-66-86</p>
					<a href="javascript:void(0);" data-href="#request" class="header__phone-descr js-popup-link">Заказать звонок</a>
				</div>
				<nav class="nav">
					<ul class="nav__list">
						<li class="nav__item">
							<a href="#services" class="nav__link">Цены</a>
						</li>
						<li class="nav__item">
							<a href="#technologies" class="nav__link">Технологии</a>
						</li>
						<li class="nav__item">
							<a href="#portfolio" class="nav__link">Работы</a>
						</li>
					</ul>
				</nav>
			</div>
		</header>
	</div>
	<div id="services" class="services">
		<div class="container clearfix">
			<div class="services__title">Наши цены</div>
			<ul class="services-list">
				{% for service in services %}
					<li data-href="#callback" class="services-list__item services-list__item_{{service.color}} js-popup-link">
						<div class="services-list__about">
							<div class="services-list__about-area">
								<div class="services-list__title">{{ service.name }}</div>
								<div class="services-list__info">{{ service.description|raw }}</div>
								<div class="services-list__price-box">
									{{ service.price }} <i class="icon-rouble"></i>
								</div>
							</div>
						</div>
						{% if service.image %}
							<img class="services-list__after" src="/uploads/{{service.image}}">
						{% endif %}
					</li>
				{% endfor %}
			</ul>
		</div>
	</div>

	<div id="portfolio" class="portfolio">
		<div class="portfolio__title">Наши работы</div>
		<ul class="portfolio-list">
			{% for work in works %}
			<li class="portfolio-list__item">
				<a href="{{ work.link }}" class="portfolio-list__link" target="_blank">
					{% if work.image %}
					<span class="portfolio-list__link_image">
						<img src="/uploads/{{ work.image }}" class="portfolio-list__link_image">
					</span>
					{% endif %}
					<span class="project_inside">
						<span class="textblock">
							<span class="caption">{{ work.name }}</span>
							<span class="anons">
								{{ work.description|raw }}
							</span>
							<span class="show">Посмотреть</span>
						</span>
					</span>
				</a>
			</li>
			{% endfor %}
		</ul>
	</div>

	<div id="technologies" class="technologies">
		<div class="technologies__title">Внедряем современные технологии</div>
		<div class="technologies__sub-title">На всю катушку используем новые технологиям программирования, дизайна и верстки без раздувания сметы проекта. В результате получаем современные и функциональные сайты по адекватной цене</div>
		<ul class="technologies-list">
			<li class="technologies-list__item">
				<div class="technologies-list__item-wrapp">
					<div class="technologies-list__col technologies-list__col_video" style="background-image:url(img/video-bg-01.png);">
					</div>
					<div class="technologies-list__col technologies-list__col_white">
						<div class="technologies-list__about-wrapp">
							<div class="technologies-list__about">
								<div class="technologies-list__title">01. Адаптивный дизайн</div>
								<p class="technologies-list__info">Сайт корректно отображается на всех типах устройств: мобильных телефонах, планшетах и широкоформатных мониторах</p>
							</div>
						</div>
					</div>
				</div>
			</li>
			<li class="technologies-list__item">
				<div class="technologies-list__item-wrapp">
					<div class="technologies-list__col technologies-list__col_white">
						<div class="technologies-list__about-wrapp">
							<div class="technologies-list__about">
								<div class="technologies-list__title">02. Отзывчивый интерфейс</div>
								<p class="technologies-list__info">Анимации помогают быстрее освоить интерфейс и разобраться с функциями еще до начала взаимодействия</p>
							</div>
						</div>
					</div>
					<div class="technologies-list__col technologies-list__col_video" style="background-image:url(img/video-bg-03.png);">
					</div>
				</div>
			</li>
			<li class="technologies-list__item">
				<div class="technologies-list__item-wrapp">
					<div class="technologies-list__col technologies-list__col_video" style="background-image:url(img/video-bg-02.png);">
					</div>
					<div class="technologies-list__col technologies-list__col_white">
						<div class="technologies-list__about-wrapp">
							<div class="technologies-list__about">
								<div class="technologies-list__title">03. Big Data и другой сложный функционал</div>
								<p class="technologies-list__info">В своей работе отталкиваемся уже на готовый функционал 1С-Битрикс, при необходимости пишем свои модули</p>
							</div>
						</div>
					</div>
				</div>
			</li>
		</ul>
		<ul class="technologies-list-image">
			<li class="technologies-list-image__item">
				<div class="technologies-list-image__img" style="background-image:url(/img/video-bg-01.png);">
				</div>
				<div class="technologies-list-image__text-wrapp">
					<div class="technologies-list-image__text">
						<div class="technologies-list-image__title">01. Адаптивный дизайн</div>
						<p class="technologies-list-image__info">Сайт корректно отображается на всех типах устройств: мобильныхтелефонах,планшетах и широкоформатных мониторах</p>
					</div>
				</div>
			</li>
			<li class="technologies-list-image__item">
				<div class="technologies-list-image__img" style="background-image:url(/img/video-bg-03.png);">
				</div>
				<div class="technologies-list-image__text-wrapp">
					<div class="technologies-list-image__text">
						<div class="technologies-list-image__title">02. Отзывчивый интерфейс</div>
						<p class="technologies-list-image__info">Анимация помогают быстрее освоить интерфейс и разобраться с функциями еще до начала взаимодействия</p>
					</div>
				</div>
			</li>
			<li class="technologies-list-image__item">
				<div class="technologies-list-image__img" style="background-image:url(/img/video-bg-02.png);">
				</div>
				<div class="technologies-list-image__text-wrapp">
					<div class="technologies-list-image__text">
						<div class="technologies-list-image__title">03. Big Data и другой сложный функционал</div>
						<p class="technologies-list-image__info">В своей работе отталкиваемся уже на готовый функционал 1С-Битрикс, при необходимости пишем свои модули</p>
					</div>
				</div>
			</li>
		</ul>
	</div>
	<div id="agency" class="about-us">
		<div class="container clearfix">
			<div class="about-us__col about-us__col_info clearfix">
				<div class="about-us__info">
					<div class="about-us__title">Мы знаем свое дело</div>
					<p class="about-us__desrc">Наше правило работы: «Делай для клиента больше, чем можешь». Мы не просто работаем по брифу — мы работаем с вами в плотном контакте, советуемся, спорим, предлагаем и оспариваем идеи.</p>
					<p class="about-us__desrc">Мы создаем эффективные решения для бизнеса. Эффективная практика в сфере маркетинга и брендинга, подкрепленная дизайнерской мыслью открывает новые пути развития бизнеса.</p>
				</div>
			</div> 
		</div>
	</div>
	<footer class="footer">
		<div class="container">
			<div class="footer__col">
				<div class="footer__col-title">Контакты</div>
				<p class="footer__phone">(495) 627-66-86</p>
				<p class="footer__phone">+79166858535</p>
				<p class="footer__phone">+380992498581 (для Украины)</p>
				<p class="footer__info">Эл. почта: mail@upitel.ru</p>
				<p class="footer__info footer__info_last">Алтуфьевское шоссе, 79д<br>Москва, Россия</p>
			</div>
			<div class="footer__col">
				<div class="footer__col-title footer__col-title_form">Задать вопрос</div>

				<!-- form -->
				<form action="#" class="form" id="question_form">
					<div class="form__box">
						<div class="form__field form__field_mini">
							<input type="text" id="question_name" name="question_name" placeholder="Как вас зовут?" class="form__input">
						</div><!--
						--><div class="form__field form__field_mini">
							<input type="tel" id="question_phone" name="question_phone" placeholder="+7 (___) ___ - __ - __" class="form__input">
						</div>
					</div>

					<div class="form__field">
						<textarea placeholder="Ваш вопрос" class="form__textarea"></textarea>
					</div>

					<div class="form__field form__field_submit">
						<input type="submit" id="question" name="question" value="Задать вопрос" class="form__submit">
					</div>
					<input type="reset" class="hidden-element" id="question_reset">
				</form>
			</div>
		</div>

		<div class="footer__bottom">
			<div class="container clearfix">
				<span class="footer__text">© {{ "now"|date("Y") }}, Upitel</span>
			</div>
		</div>
	</footer>
	<div class="hidden-element">
		<div class="popup popup_std" id="request">
			<a href="javascript:void(0);" class="popup__close arcticmodal-close"></a>
			<p class="popup__title">Заявка на консультацию</p>
			<div class="popup__content">
				<form action="#" class="form form_popup" id="cons_form">
					<div class="form__field form__field_mini">
						<input type="text" class="form__input" id="cons_name" name="cons_name" placeholder="Как вас зовут?">
					</div><!--
					--><div class="form__field form__field_mini">
						<input type="tel" class="form__input" id="cons_phone" name="cons_phone" placeholder="+7 (___) ___ - __ - __">
					</div>
					<div class="form__field">
						<textarea class="form__textarea" id="cons_comment" name="cons_comment" placeholder="Ваш комментарий"></textarea>
					</div>
					<div class="form__field form__field_submit">
						<input type="submit" data-href="#success" class="form__submit" value="Получить консультацию">
					</div>
					<input type="reset" class="hidden-element" id="cons_reset">
				</form>
			</div>
		</div>
		<div class="order_popup popup popup_std" id="callback">
			<div class="popup__content">
				<a href="javascript:void(0);" class="popup__close arcticmodal-close"></a>
				<form action="#" class="form form_popup clearfix" id="shop_form">
					<div class="form_title">
						Расскажем об услуге и предложим решение
					</div>
					<div class="form__field form__field_mini">
						<input type="text" class="form__input" id="shop_name" name="shop_name" placeholder="Как вас зовут?">
					</div><!--
					--><div class="form__field form__field_mini">
						<input type="tel" class="form__input" id="shop_phone" name="shop_phone" placeholder="+7 (___) ___ - __ - __">
					</div>
					<div class="form__field form__field_submit">
						<input type="submit" data-href="#success" class="form__submit" value="Получить консультацию">
					</div>
					<input type="reset" class="hidden-element" id="shop_reset">
				</form>
			</div>
		</div>
	</div>
	<div class="hidden-element">
		<div class="popup popup_std" id="ok">
			<a href="javascript:void(0);" class="popup__close arcticmodal-close"></a>
			<p class="popup__title">Отправлено</p>
			<div class="popup__content">
				<p>Спасибо за заявку, менеджер свяжется с вами в течении 15 мин</p>
			</div>
		</div>
	</div>
	<button data-href="#ok" class="js-popup-link hidden-element" id="thanks">Спасибо</button>
	<div class="md-overlay"></div>
{% endblock %}

templates/default/page.html.twig
{% extends 'base.html.twig' %}

{% block title %}{{ page.title }}{% endblock %}

{% block meta %}
	{% if page.metaTitle %}
	<meta name="title" content="{{ page.metaTitle }}">
	{% endif %}
	{% if page.metaDesc %}
	<meta name="description" content="{{ page.metaDesc }}">
	{% endif %}
	{% if page.metaKeywords %}
	<meta name="keywords" content="{{ page.metaKeywords }}">
	{% endif %}
{% endblock %}

{% block body %}
	<header class="header header-colored">
			<div class="container clearfix">
				<a href="/" class="header__logo">
					<span class="header__logo-text">Разработка современных<br>интернет-проектов.</span>
				</a>
				<div class="header__phone">
					<p class="header__phone-number">(495) 627-66-86</p>
					<a href="javascript:void(0);" data-href="#request" class="header__phone-descr js-popup-link">Заказать звонок</a>
				</div>
				<nav class="nav">
					<ul class="nav__list">
						<li class="nav__item">
							<a href="#services" class="nav__link">Цены</a>
						</li>
						<li class="nav__item">
							<a href="#technologies" class="nav__link">Технологии</a>
						</li>
						<li class="nav__item">
							<a href="#portfolio" class="nav__link">Работы</a>
						</li>
					</ul>
				</nav>
			</div>
	</header>
	
	<main class="static">
		<div class="container">
			{{ page.text|raw }}
		</div>
	</main>

	<footer class="footer">
		<div class="container">
			<div class="footer__col">
				<div class="footer__col-title">Контакты</div>
				<p class="footer__phone">(495) 627-66-86</p>
				<p class="footer__phone">+79166858535</p>
				<p class="footer__phone">+380992498581 (для Украины)</p>
				<p class="footer__info">Эл. почта: mail@upitel.ru</p>
				<p class="footer__info footer__info_last">Алтуфьевское шоссе, 79д<br>Москва, Россия</p>
			</div>
			<div class="footer__col">
				<div class="footer__col-title footer__col-title_form">Задать вопрос</div>

				<!-- form -->
				<form action="#" class="form" id="question_form">
					<div class="form__box">
						<div class="form__field form__field_mini">
							<input type="text" id="question_name" name="question_name" placeholder="Как вас зовут?" class="form__input">
						</div><!--
						--><div class="form__field form__field_mini">
							<input type="tel" id="question_phone" name="question_phone" placeholder="+7 (___) ___ - __ - __" class="form__input">
						</div>
					</div>

					<div class="form__field">
						<textarea placeholder="Ваш вопрос" class="form__textarea"></textarea>
					</div>

					<div class="form__field form__field_submit">
						<input type="submit" id="question" name="question" value="Задать вопрос" class="form__submit">
					</div>
					<input type="reset" class="hidden-element" id="question_reset">
				</form>
			</div>
		</div>

		<div class="footer__bottom">
			<div class="container clearfix">
				<span class="footer__text">© {{ "now"|date("Y") }}, Upitel</span>
			</div>
		</div>
	</footer>
	<div class="hidden-element">
		<div class="popup popup_std" id="request">
			<a href="javascript:void(0);" class="popup__close arcticmodal-close"></a>
			<p class="popup__title">Заявка на консультацию</p>
			<div class="popup__content">
				<form action="#" class="form form_popup" id="cons_form">
					<div class="form__field form__field_mini">
						<input type="text" class="form__input" id="cons_name" name="cons_name" placeholder="Как вас зовут?">
					</div><!--
					--><div class="form__field form__field_mini">
						<input type="tel" class="form__input" id="cons_phone" name="cons_phone" placeholder="+7 (___) ___ - __ - __">
					</div>
					<div class="form__field">
						<textarea class="form__textarea" id="cons_comment" name="cons_comment" placeholder="Ваш комментарий"></textarea>
					</div>
					<div class="form__field form__field_submit">
						<input type="submit" data-href="#success" class="form__submit" value="Получить консультацию">
					</div>
					<input type="reset" class="hidden-element" id="cons_reset">
				</form>
			</div>
		</div>
		<div class="order_popup popup popup_std" id="callback">
			<div class="popup__content">
				<a href="javascript:void(0);" class="popup__close arcticmodal-close"></a>
				<form action="#" class="form form_popup clearfix" id="shop_form">
					<div class="form_title">
						Расскажем об услуге и предложим решение
					</div>
					<div class="form__field form__field_mini">
						<input type="text" class="form__input" id="shop_name" name="shop_name" placeholder="Как вас зовут?">
					</div><!--
					--><div class="form__field form__field_mini">
						<input type="tel" class="form__input" id="shop_phone" name="shop_phone" placeholder="+7 (___) ___ - __ - __">
					</div>
					<div class="form__field form__field_submit">
						<input type="submit" data-href="#success" class="form__submit" value="Получить консультацию">
					</div>
					<input type="reset" class="hidden-element" id="shop_reset">
				</form>
			</div>
		</div>
	</div>
	<div class="hidden-element">
		<div class="popup popup_std" id="ok">
			<a href="javascript:void(0);" class="popup__close arcticmodal-close"></a>
			<p class="popup__title">Отправлено</p>
			<div class="popup__content">
				<p>Спасибо за заявку, менеджер свяжется с вами в течении 15 мин</p>
			</div>
		</div>
	</div>
	<button data-href="#ok" class="js-popup-link hidden-element" id="thanks">Спасибо</button>
	<div class="md-overlay"></div>
{% endblock %}

templates/security/login.html.twig
{% if error %}
    <div>{{ error.messageKey|trans(error.messageData, 'security') }}</div>
{% endif %}

<form action="{{ path('login') }}" method="post">
    <label for="username">Username:</label>
    <input type="text" id="username" name="_username" value="{{ last_username }}" />

    <label for="password">Password:</label>
    <input type="password" id="password" name="_password" />

    {#
        If you want to control the URL the user
        is redirected to on success (more details below)
        <input type="hidden" name="_target_path" value="/account" />
    #}

    <button type="submit">login</button>
</form>